.TH grism 1 2007\-09\-27
.SH NAME
Grism \- An open source, stock market observation tool.
.SH SYNOPSIS
.B grism
.SH DESCRIPTION
.B Grism
allows you to easily track the evolution of stock prices
through watchlists, portfolios and charts.
.PP
Grism uses Yahoo! Finance for its quote data.
This means that with Grism, you can observe stocks, ETFs, indices
and mutual funds from every major stock market in the world.
All you need is the stock's symbol that interests you.
.PP
Grism is GUI-only and does not have a command-line interface.
.PP
Major Features:
.PP
* Watchlists - Monitor the evolution of a stock's price from a
starting price through the last trade.
.PP
* Portfolios - See the current gain/loss calculation for a set of stocks.
.PP
* Charts - View dynamic, historical price charts for monitored stocks.
.SH AVAILABILITY
Grism is free software, licensed under the terms of the
GNU General Public License as published by the Free Software Foundation.
A copy of that license should been distributed along with this software
in the file COPYING. You are encouraged to distribute copies of Grism,
but please obey the terms of this license.
.PP
The latest version of Grism can be obtained via the project\(cqs
webpage: http://www.grism.org
.SH AUTHOR
Nicholas Rahn <nick@transparentech.com>
.PP
This manual page was written by Federico Pampana <fedefede0101@gmail.com>
